version: 2
registries:
  maven-repository-repo-bazaarvoice-com-nexus-content-groups-bazaa:
    type: maven-repository
    url: https://repo.bazaarvoice.com/nexus/content/groups/bazaarvoice/
    username: release
    password: "${{secrets.MAVEN_REPOSITORY_REPO_BAZAARVOICE_COM_NEXUS_CONTENT_GROUPS_BAZAA_PASSWORD}}"

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.owasp:dependency-check-maven
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.1.3
    - 6.1.4
  registries:
  - maven-repository-repo-bazaarvoice-com-nexus-content-groups-bazaa
